### ISSUE TITLE
Skyeye Container crashes on startup on Sandy Bridge CPU

### ISSUE THREAD

**Issue by Rabbit994** [dharmab/skyeye#262] opened 2024-09-04 17:48 UTC
**Describe the bug**

Container crashes on the startup in Kubernetes cluster with no GPU.

**Steps to Reproduce**

Start up the container ghcr.io/dharmab/skyeye:latest with following ENV Variables:

SKYEYE_WHISPER_MODEL=/model/ggml-small.en.bin
SKYEYE_TELEMETRY_ADDRESS=<REMOVED>
SKYEYE_SRS_SERVER_ADDRESS=<REMOVED>
SKYEYE_SRS_EAM_PASSWORD=blue
SKYEYE_SRS_FREQUENCIES=130.0AM,271.5AM
SKYEYE_CALLSIGN=FOCUS
SKYEYE_COALITION=blue
SKYEYE_VOICE=feminine
SKYEYE_AUTO_PICTURE=false
SKYEYE_AUTO_PICTURE_INTERVAL
SKYEYE_THREAT_MONITORING=true
SKYEYE_THREAT_MONITORING_INTERVAL=3m
SKYEYE_MANDATORY_THREAT_RADIUS=25
SKYEYE_LOG_LEVEL=info
SKYEYE_LOG_FORMAT=pretty

**Logs**

[skyeye-deploy-5df5d76d5f-vbn7c_skyeye_2024-09-04T17-32-31.txt](https://github.com/user-attachments/files/16874715/skyeye-deploy-5df5d76d5f-vbn7c_skyeye_2024-09-04T17-32-31.txt)

**Platform Info**

What does `./skyeye.exe --version` / `./skyeye --version` output?

skyeye version devel (Captured from the pod)

What OS are you running SkyEye on?

Kubernetes node Host is Ubuntu 22.04 LTS

What CPU does the hardware have? How much RAM?

Host has 16 Cores, older Xeon processor. Kubernetes restricts the container 7 cores. It's RAM limited to 12Gi but removing limits doesn't change anything. (https://www.intel.com/content/www/us/en/products/sku/64596/intel-xeon-processor-e52690-20m-cache-2-90-ghz-8-00-gts-intel-qpi/specifications.html)

Are you running any other software besides SkyEye on this machine?
 
Yea, there is other containers running, nothing CPU/RAM intensive.

**Comment by dharmab** [comment] 2024-09-05 03:03
Hi @Rabbit994! Thanks for trying SkyEye.

First off- the container image is marked as experimental. I tore down my in-home Kubernetes cluster and repurposed it as a Jellyfin server a while back, so I don't have a good k8s test environment for the container and can't guarantee it works for any given build. So you might have to do some troubleshooting legwork 😅

From the logs it looks like something in whisper.cpp is crashing, I don't know what though. 🤔

I'll hope over to a Linux machine and see if I can reproduce the problem.

**Comment by dharmab** [comment] 2024-09-05 03:17
I figured it out.

Your CPU is very, very old and lacks support for [AVX2](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Advanced_Vector_Extensions_2). [AVX2 is required by whisper.cpp](https://github.com/ggerganov/whisper.cpp/issues/238#issuecomment-1343414568).

I have a backlog ticket to add support for cloud-based speech recognition (#162), but it will be weeks or months until I get around to it, as I am focusing on stability/performance/quality issues before new features. In the meantime, I will update the admin guide with a note about this requirement. Sorry for the inconvenience, and thank you for spending the time to collect the logs and open the issue!

In the meantime, you can try SkyEye using a Hetzner CCX23 instance for about 0.05 Euro an hour (or around 1 Euro a day if you want a 24/7 instance).

**Comment by Rabbit994** [comment] 2024-09-05 15:35
Thanks for the update. I've got older i7-7700k I was going to turn into cluster as well. I'll try and report back.

**Closed** 2024-09-05 16:17 UTC
Labels: documentation, operations
